Repository Eveheeero/fireman, pull requests merged in 2023-08, with the labels that each got.

#20 Add x64's addsubps, adox, aesdec, aesdec128kl instruction documentation
  iceball/src/x64/statement.rs
Labels: Documentation

#21 Instruction to ir statement
  .github/workflows/rust.yml
  Cargo.toml
  dryice/Cargo.toml
  dryice/src/lib.rs
  dryice/src/main.rs
  fireball/Cargo.toml
  fireball/src/arch/mod.rs
  fireball/src/arch/x86_64/instruction_analyze.rs
  fireball/src/arch/x86_64/mod.rs
  fireball/src/core/instruction.rs
  fireball/src/ir/arm/mod.rs
  fireball/src/ir/data.rs
  fireball/src/ir/mod.rs
  fireball/src/ir/operator.rs
  fireball/src/ir/register.rs
  fireball/src/ir/statements.rs
  fireball/src/ir/x86_64.rs
  fireball/src/ir/x86_64/base.rs
  fireball/src/ir/x86_64/mod.rs
  fireball/src/ir/x86_64/mut.rs
  fireball/src/ir/x86_64/range.rs
  fireball/src/pe/fire.rs
  fireball/src/pe/fire/decom_from_entry.rs
  iceball/Cargo.toml
  iceball/src/lib.rs
  iceball/src/x64.rs
  iceball/src/x64/register.rs
  iceball/src/x64/statement.rs
Labels: Documentation, Enhancement

#17 Change main logic to IR based
  .github/workflows/rust.yml
  Cargo.toml
  README.md
  dryice/Cargo.toml
  dryice/src/lib.rs
  dryice/src/main.rs
  fireball/Cargo.toml
  fireball/src/arch/mod.rs
  fireball/src/arch/x86_64/instruction_analyze.rs
  fireball/src/arch/x86_64/mod.rs
  fireball/src/arch/x86_64/op_parse.rs
  fireball/src/arch/x86_64/op_patterns.rs
  fireball/src/arch/x86_64/register.rs
  fireball/src/core/address.rs
  fireball/src/core/block.rs
  fireball/src/core/blocks.rs
  fireball/src/core/fire.rs
  fireball/src/core/instruction.rs
  fireball/src/core/instruction_history.rs
  fireball/src/core/mod.rs
  fireball/src/core/pre_defined_offset.rs
  fireball/src/core/pre_defined_offsets.rs
  fireball/src/core/relation.rs
  fireball/src/core/relations.rs
  fireball/src/core/section.rs
  fireball/src/core/sections.rs
  fireball/src/ir/arm/mod.rs
  fireball/src/ir/data.rs
  fireball/src/ir/mod.rs
  fireball/src/ir/operator.rs
  fireball/src/ir/register.rs
  fireball/src/ir/statements.rs
  fireball/src/ir/x86_64/base.rs
  fireball/src/ir/x86_64/mod.rs
  fireball/src/ir/x86_64/mut.rs
  fireball/src/ir/x86_64/range.rs
  fireball/src/lib.rs
  fireball/src/pe/_pe.rs
  fireball/src/pe/asm.rs
  fireball/src/pe/fire.rs
  fireball/src/pe/fire/decom_from_entry.rs
  fireball/src/pe/fire/parse_block.rs
  fireball/src/pe/fmt.rs
  fireball/src/pe/mod.rs
  fireball/src/prelude.rs
  fireball/src/tests/mod.rs
  fireball/src/utils/error.rs
  fireball/src/utils/mod.rs
  fireball/tests/hello_world.rs
  fireman/src/main.rs
  iceball/Cargo.toml
  iceball/src/lib.rs
  iceball/src/x64.rs
  iceball/src/x64/register.rs
  iceball/src/x64/statement.rs
Labels: Enhancement

#22 Update README.md
  README.md
Labels: Documentation
